export const campaignConstant = {
  GET_CAMPAIGNS_START: "GET_CAMPAIGNS_START",
  GET_CAMPAIGNS_SUCCESS: "GET_CAMPAIGNS_SUCCESS",
  GET_CAMPAIGNS_FAILURE: "GET_CAMPAIGNS_FAILURE",
  READ_CAMPAIGN_START: "READ_CAMPAIGN_START",
  READ_CAMPAIGN_SUCCESS: "READ_CAMPAIGN_SUCCESS",
  READ_CAMPAIGN_FAILURE: "READ_CAMPAIGN_FAILURE"
};
