export const opentokConstant = {
  INITIALIZE_OPENTOK_START: "INITIALIZE_OPENTOK_START",
  INITIALIZE_OPENTOK_SUCCESS: "INITIALIZE_OPENTOK_SUCCESS",
  INITIALIZE_OPENTOK_FAILURE: "INITIALIZE_OPENTOK_FAILURE",
  UPDATE_SUBSCRIBERS_LIST: "UPDATE_SUBSCRIBERS_LIST"
};
  