export const opentokConstant = {
  ALERT_ERROR_MESSAGE: "ALERT_ERROR_MESSAGE",
  HIDE_START_BUTTON: "HIDE_START_BUTTON",
  INITIALIZE_OPENTOK_START: "INITIALIZE_OPENTOK_START",
  UPDATE_SUBSCRIBERS_LIST: "UPDATE_SUBSCRIBERS_LIST",
  VIDEO_CALL_DISCONNECTED: "VIDEO_CALL_DISCONNECTED"
};
  